[WIP] Add the GCM and CCM modes for OpenSSL with PHP 7.1
zendframework/zend-crypt pull request #38
Opened 2016-11-09 18:58 UTC by ezimuel

This PR adds the GCM and CCM authenticated encryption mode for OpenSSL for PHP 7.1. This is a new feature of PHP 7.1 proposed in [PHP RFC: OpenSSL AEAD support](https://wiki.php.net/rfc/openssl_aead).
Read [this blog post](http://www.zimuel.it/authenticated-encrypt-with-openssl-and-php-7-1/) for more information about the usage of these encryption modes in PHP.
I've updated the `Zend\Crypt\BlockCipher` documentation for this new feature.

**Note:** The unit tests are failing on PHP 7.1RC5 for `ZendTest\Crypt\PublicKey\DiffieHellmanTest::testWithBinaryFormsAndLargeIntegersAndOpenssl`. The issue seems to be related to the functions `openssl_pkey_new()`. I opened the bug [#73478](https://bugs.php.net/bug.php?id=73478) on bugs.php.net. 
*Please note that this bug is not related with the code submitted with this PR!*

2016-11-10 15:47 UTC, weierophinney requested changes
I've noted a few documentation and code changes. Please also find somebody with crypto experience to review, as I'm not certain I can review for correctness of the algorithms. :smile:

2016-11-10 15:47 UTC, weierophinney commented on doc/book/block-cipher.md
> +the mode in the factory. For instance, here is reported an example that uses
"For instance, the following is an example ... "

2016-11-10 15:47 UTC, weierophinney commented on doc/book/block-cipher.md
> +And here is repoted the factory for `aes-256-ccm` algorithm:
"And below is an example demonstrating the factory for ..."

2016-11-10 15:47 UTC, weierophinney commented on doc/book/block-cipher.md
> +> have specific requirements.
"; we recommend using GCM unless you have requirements that dictate CCM."

2016-11-10 15:47 UTC, weierophinney commented on src/Symmetric/Mcrypt.php
> +                'We suggest to use Zend\Crypt\Symmetric\Openssl.',
Move the concatenation operator to the second line:

```php
'The Mcrypt extension is deprecated from PHP 7.1+. '
. 'We suggest to use Zend\Crypt\Symmetric\Openssl.',
```

2016-11-10 15:47 UTC, weierophinney commented on src/Symmetric/Openssl.php
> +            $this->encryptionModes[] = 'ccm';
Maybe make this:

```php
array_push($this->encryptionModes, 'gcm', 'ccm');
```

2016-11-10 15:47 UTC, weierophinney commented on src/Symmetric/Openssl.php
> +        }
These previous two blocks are repeated in `setAad()`; perhaps you could extract those validations to a separate method?

2016-11-15 15:22 UTC, ezimuel commented on src/Symmetric/Openssl.php
> +        }
@weierophinney the exception message in setAad() was wrong, I fixed with:
"You can set Additional Authentication Data (AAD) only for CCM or GCM mode"

2016-11-15 17:25 UTC, ezimuel commented on doc/book/block-cipher.md
> +the mode in the factory. For instance, here is reported an example that uses
Fixed

2016-11-15 17:25 UTC, ezimuel commented on doc/book/block-cipher.md
> +And here is repoted the factory for `aes-256-ccm` algorithm:
Fixed

2016-11-15 17:25 UTC, ezimuel commented on doc/book/block-cipher.md
> +> have specific requirements.
Fixed

2016-11-15 17:25 UTC, ezimuel commented on src/Symmetric/Mcrypt.php
> +                'We suggest to use Zend\Crypt\Symmetric\Openssl.',
Fixed

2016-11-15 17:25 UTC, ezimuel commented on src/Symmetric/Openssl.php
> +            $this->encryptionModes[] = 'ccm';
Changed

2016-11-16 18:29 UTC, ezimuel commented
@weierophinney I changed the code according to your feedback.

2016-11-16 18:32 UTC, ezimuel commented
@paragonie-scott if you have time, I would like to have your feedback on this PR, thanks!

2016-11-16 19:33 UTC, weierophinney commented on src/Symmetric/Openssl.php
> +        }
Perfect.

2016-11-16 19:34 UTC, weierophinney approved these changes
Changes look good!

2016-11-16 20:41 UTC, paragonie-scott commented on test/Symmetric/OpensslAeadTest.php
> +
Interesting mix of `strlen()` and `mb_substr()`. Probably no practical consequence here.

In the future, it may be a good idea to add [constant_time_encoding](https://github.com/paragonie/constant_time_encoding) as a dependency and use the `Binary` class everywhere. (It's MIT licensed IIRC.)

2016-11-16 20:43 UTC, paragonie-scott commented on test/Symmetric/McryptDeprecatedTest.php
> +        if (PHP_VERSION_ID < 70100) {
~~Shouldn't this be `>=` for skipping the tests?~~ Nevermind, I need more coffee.

2016-11-16 20:46 UTC, paragonie-scott commented on test/BlockCipher/McryptTest.php
> +
Extra whitespace line. (I feel really pedantic for pointing this one out here, but so far I haven't seen any actual logic errors or vulnerabilities.)

2016-11-16 20:51 UTC, paragonie-scott commented
:+1: Looks great.

2016-11-17 13:48 UTC, ezimuel commented on test/Symmetric/OpensslAeadTest.php
> +
I changed strlen() usage in favor of mb_strlen(). Thanks for your library, I'll use it in the future!

2016-11-17 13:49 UTC, ezimuel commented on test/Symmetric/McryptDeprecatedTest.php
> +        if (PHP_VERSION_ID < 70100) {
No problem :)

2016-11-17 13:49 UTC, ezimuel commented on test/BlockCipher/McryptTest.php
> +
No pedantic at all, I fixed the CS. Thanks a ton for your review!

2016-11-30 08:58 UTC, ezimuel commented
@weierophinney can you merge this PR? Thanks!

2016-11-30 09:43 UTC, Ocramius commented
@ezimuel I took ownership of the branch and am merging it.

2016-11-30 10:08 UTC, merged

2016-11-30 10:08 UTC, Ocramius commented
@ezimuel merged \o/

I applied a series of non-functional code-style-related fixes, feel free to check commits referenced here.

2016-11-30 10:09 UTC, Ocramius commented
@ezimuel also, release if you can ;-)